name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date)
      
      
    - name: Scan image
      uses: Azure/container-scan@v0
      with:
        image-name: my-image-name:$(date)
        severity-threshold: CRITICAL
        run-quality-checks: true
